### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by mmunozpatino** [Mockgoose/Mockgoose#67] opened 2017-12-06 23:37 UTC
my app.js
![image](https://user-images.githubusercontent.com/23423556/33691057-29656b0e-dac5-11e7-9f54-c64fef37a67c.png)
when i run mocha --120000
![image](https://user-images.githubusercontent.com/23423556/33691067-3d58fa0e-dac5-11e7-80c5-a1cde98fcfd3.png)

**Comment by sjorssnoeren** [comment] 2017-12-07 08:22
This issue is already being discussed. #64

**Comment by vladotesanovic** [comment] 2017-12-07 08:31
Specify like this:

```
mongoose.Promise = global.Promise;
mockgoose.helper.setDbVersion('3.4.3');
```
same for you @sjorssnoeren

**Comment by sjorssnoeren** [comment] 2017-12-07 09:53
@vladotesanovic Thanks so much, fixes everything.

**Comment by oldschoolbg** [comment] 2017-12-11 08:31
I've just tried the above three or four times in a row, clearing npm etc, and it still does not work.

*goes back to hand rolled mongoose fake database*

**Comment by vladotesanovic** [comment] 2017-12-11 08:53
@oldschoolbg 
you need to install 'mockgoose-fix', set db version than ``` npm install ```

**Comment by wangxuepeng** [comment] 2017-12-14 07:25
This dose work.

**Comment by binary1230** [comment] 2017-12-19 17:03
struggling to get mockgoose working, here's what worked for me, just verified in a from-scratch install.  This uses the temporary ```mockgoose-fix``` library, so when this bug is all fixed up, people will want to just use ```mockgoose`` again.



0) navigate to an empty directory
1) ```npm init -f```
2) ```npm install --save mongoose mongodb```
3) ```npm install --save-dev mockgoose-fix babel-core babel-preset-es2015 babel-cli```
4) put this in index.js:

```
import * as mongoose from 'mongoose';
import {Mockgoose} from 'mockgoose-fix';

let mockgoose = new Mockgoose(mongoose);

mockgoose.prepareStorage().then(() => {
    mongoose.connect('mongodb://foobar/baz');
    mongoose.connection.on('connected', () => {
        console.log('db connection is now open');
    });
}).catch((err) => {console.log(err)});
```

5) run: ```node_modules/babel-cli/bin/babel-node.js index.js --presets=es2015```

----
my npm --version = 5.6.0
my node --version = v8.9.1

Doing the steps above gets me past THIS issue, but I immediately then run into https://github.com/Mockgoose/Mockgoose/issues/56 and I still can't use mongoose. 

haaaaalllp :)

**Comment by f3ltron** [comment] 2018-01-12 19:04
i think it's about () => {} es6 syntaxe you loose context of this and other possible context so not work

**Comment by LoneRifle** [comment] 2018-11-26 13:42
As discussed - duplicate of #64

**Closed by LoneRifle** 2018-11-26 13:42 UTC
